### ISSUE TITLE
Redundant AID request

### ISSUE THREAD

**Issue by riccardolunardi** [piotrekwitkowski/LibraryReader#3]
Hello,
I was wondering why the reader and the "card" have to exchange the application AID (015548), when the application has already an AID, which is set on the .xml file.
Wouldn't it be redundant to ask for another AID, when, if both devices have established a connection, already have shared the AID (the one in the .xml)?

Let me know if I have been clear enough!

**Comment by piotrekwitkowski** [comment]
It is somehow redundant, but my goal for the app was different - it was to emulate the whole card and it's multiple Applications if necessary. It works nice if your place, let's say, library, has already multiple Applications on a current physical card, for example 1) for card borrowing, 2) for lockers/some room access, 3) wallet for the cafeteria. Then you could argue, a user needs just one Android app instead of three and that's what you may need a two-level AID "routing" for.

Moreover, the goal of the app was to show that although it is possible to emulate the whole DESFire infrastructure, multiple applications, auth mechanisms, types of files and so on, you _probably shouldn't want this_. Your whole applications' data and key material isn't hardware-secured anymore. If, for example, a phone is rooted, you can easily read the data and keys from the app. The app will work and can be compatible with your existing DESFire readers for your DESFire cards - but it won't be secure.

If you want to replace a card-based solution with a HCE-based one, please read more about HCE security and tokenization mechanisms. Hope this makes the design decisions a little bit clearer for you now :)

**Comment by riccardolunardi** [comment]
Thank you for the clarification!
